In [1]:
import numpy as np
import matplotlib.pyplot as plt
from dataclasses import astuple


In [2]:
n = 3
k = 1
mask = np.full(n, True)
mask[k] = False
x = np.arange(2*n)
y = x[np.concatenate([mask,mask])]
y

array([0, 2, 3, 5])

In [3]:
x = np.arange(10)
np.delete(x,(3,4))

array([0, 1, 2, 5, 6, 7, 8, 9])

In [4]:
n = 10
x,w = np.polynomial.legendre.leggauss(n)
y = np.array([np.exp(-1j*k) for k in range(n)])
a = np.polynomial.legendre.legfit(x,y,deg=10)
print(y)

[ 1.        -0.j          0.54030231-0.84147098j -0.41614684-0.90929743j
 -0.9899925 -0.14112001j -0.65364362+0.7568025j   0.28366219+0.95892427j
  0.96017029+0.2794155j   0.75390225-0.6569866j  -0.14550003-0.98935825j
 -0.91113026-0.41211849j]


/home/jakob/Documents/OneDriveDTU/10-semester/speciale/code/genquad-venv/lib/python3.10/site-packages/numpy/polynomial/legendre.py:1412: RankWarning: The fit may be poorly conditioned
  return pu._fit(legvander, x, y, deg, rcond, full, w)


In [5]:
z = 10 + 9*1j
np.sqrt(z)*np.sqrt(z)

(10+9j)

In [6]:
x,w = np.polynomial.legendre.leggauss(10)
np.outer(w,w).sum()

4.0

In [7]:
x = np.array([1,2])
def f(x,y):
    return x + y

x = (0,1) + ("",)
y = (x,)
print(x)

(0, 1, '')


In [8]:
x = 10
def tupleize(x):
    if type(x) is not tuple:
        x = (x,)
    return x

In [9]:
x = np.arange(100)
print(x.reshape((10,10)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
X = [[x for x in range(k)] for k in range(10)]
X

[[],
 [0],
 [0, 1],
 [0, 1, 2],
 [0, 1, 2, 3],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5, 6],
 [0, 1, 2, 3, 4, 5, 6, 7],
 [0, 1, 2, 3, 4, 5, 6, 7, 8]]

In [11]:
import plotly.graph_objects as go
import numpy as np
from scipy.special import sph_harm

l_ = 1
m_ = 1

theta = np.pi/2
phi = 0

# Watch out for order of arguments, it's different than in SymPy!
sph_harm(m_, l_, phi, theta)


# Define the 1-dimensional coordinate axes:
theta = np.linspace(0, np.pi, 100)
phi = np.linspace(0, 2*np.pi, 100)

# Make a 2D-meshed grid out of the axes:
Theta, Phi = np.meshgrid(theta, phi, indexing="ij")


sph_harm(m_, l_, Phi, Theta)

def create_figure(l, m):
    """Create a figure of Y_lm using Plotly."""

    thetas = np.linspace(0, np.pi, 100)
    phis = np.linspace(0, 2*np.pi, 100)
    
    Thetas, Phis = np.meshgrid(thetas, phis)
    
    ylm = sph_harm(m, l, Phi, Theta)

    fcolors = ylm.real
    fmax, fmin = fcolors.max(), fcolors.min()
    fcolors = (fcolors - fmin)/(fmax - fmin)

    R = abs(ylm)
    X = R * np.sin(Theta) * np.cos(Phi)
    Y = R * np.sin(Theta) * np.sin(Phi)
    Z = R * np.cos(Theta)

    
    fig = go.Figure(
                data=[
                    go.Surface(
                        x=X, y=Y, z=Z, 
                        surfacecolor=fcolors,
                        colorscale='balance', showscale=False, 
                        opacity=1.0, hoverinfo='none',
                    )
                ]
    )

    fig.update_layout(title='$Y_{%d%d}$' % (l, m), autosize=False,
                      width=700, height=700,
                      margin=dict(l=65, r=50, b=65, t=90)
    )
    return fig

In [12]:
create_figure(1,1)

In [16]:
m=1
l=1

thetas = np.linspace(0, np.pi, 100)
phis = np.linspace(0, 2*np.pi, 100)

Thetas, Phis = np.meshgrid(thetas, phis)

ylm = sph_harm(m, l, Phi, Theta)

fcolors = ylm.real
fmax, fmin = fcolors.max(), fcolors.min()
fcolors = (fcolors - fmin)/(fmax - fmin)

R = abs(ylm)
X = R * np.sin(Theta) * np.cos(Phi)
Y = R * np.sin(Theta) * np.sin(Phi)
Z = R * np.cos(Theta)


fig = go.Figure(
            data=[
                go.Surface(
                    x=X, y=Y, z=Z, 
                    surfacecolor=fcolors,
                    colorscale='balance', showscale=False, 
                    opacity=1.0, hoverinfo='none',
                )
            ]
)

fig.update_layout(title='$Y_{%d%d}$' % (l, m), autosize=False,
                    width=700, height=700,
                    margin=dict(l=65, r=50, b=65, t=90)
)