In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from dataclasses import astuple


In [2]:
N = 3
a = np.random.normal(size=(3,3))
b = np.random.normal(size=(3,3))
A = a + 1j*b
rhs = np.random.normal(size=3)

Q,R = sp.linalg.qr(A)
sp.linalg.norm(Q@R-A)

x1 = np.linalg.solve(Q,rhs)



# print(x1)

# print(Q@Q.T.conj())
U = np.diag((x1*abs(x1)**(-1)))
Q2 = Q@U
print(np.around(Q2@Q2.T.conj(),1))
x2 = np.linalg.solve(Q2,rhs)
print(x2)

[[ 1.+0.j -0.-0.j  0.+0.j]
 [-0.+0.j  1.+0.j  0.-0.j]
 [ 0.-0.j  0.+0.j  1.+0.j]]
[1.08213432+0.00000000e+00j 1.11690721-1.11022302e-16j
 0.36091326-1.38777878e-17j]


In [19]:
def sherman_morrison(Ainv,u,v):
    ''' finds (A + uv^T)^-1 using a rank-1 update'''
    assert Ainv.flags['F_CONTIGUOUS']
    Ainvu = Ainv @ u
    alpha = -1 / (1 + v.T @ Ainvu)
    sp.linalg.blas.dger(alpha, Ainvu, v.T @ Ainv, a=Ainv, overwrite_a=1)


In [20]:
import numpy as np
A = np.random.normal(size=(3,3))
A = np.asfortranarray(A)
print(A.flags)
u = np.random.normal(size=(3,))
v = np.random.normal(size=(3,))

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [40]:
eta = np.array([0.1,0.2,0.01,100,1])
idx = np.argsort(eta)
idx = np.flip(idx)
print(idx)

[3 4 1 0 2]


In [37]:
A = np.asfortranarray(np.ones(shape=(4,4)))
B = A
print(B.flags)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [34]:
print(np.linalg.inv(A+np.outer(u,v)))
B = np.asfortranarray(np.linalg.inv(A))
sherman_morrison(B,u,v)
print(B)

[[-1.2950566  -5.75988655 -7.49836786]
 [ 0.03193483  0.54472349 -0.77721822]
 [ 0.08075092  3.1853387   4.65612454]]
[[-1.2950566  -5.75988655 -7.49836786]
 [ 0.03193483  0.54472349 -0.77721822]
 [ 0.08075092  3.1853387   4.65612454]]


In [29]:
A = np.random.normal(size=(3,3))
B = np.asfortranarray(A)
print(A)
print(B)

[[-1.34990713 -0.47592627 -1.52002989]
 [ 0.81244405  0.88775272  0.25058853]
 [-1.59682167 -0.51267754  0.02547754]]
[[-1.34990713 -0.47592627 -1.52002989]
 [ 0.81244405  0.88775272  0.25058853]
 [-1.59682167 -0.51267754  0.02547754]]


In [ ]:
sp.special.sph_harm(30,131,1,1)

(-0.02957846326764082+0.1894598535170757j)

In [ ]:
a = [
    def f(x):
        return a:
    ]

SyntaxError: invalid syntax (2237672880.py, line 2)